### ISSUE TITLE
Static website?

### ISSUE THREAD

**Issue by mattyellow** [shannonpeng/shannonpeng.com#1]
Hi! I really like your website and would like to run it as a static website through GitHub pages. Could you release a static version or a jekyll version of your site? I think it would be really helpful for others too, as they could benefit from such beautiful interface

**Comment by shannonpeng** [comment]
Hey, thanks! Hm, I didn't intend for my website to be used as a template so I'll have to think about that. How did you find it?

**Comment by shannonpeng** [comment]
Hey, I've decided not to do this, but I'll be sure to let you know if I make any portfolio website templates in the future!
